# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rapyd-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://rapyd.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ff027bfc3da9422a9bec26cdb951ef3d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_3bccef0f245c403792478c1c1d69c4b2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: rapyd.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ff027bfc3da9422a9bec26cdb951ef3d }}/rapyd-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rapyd-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5779480743aa476889f32ead42955850 }}
        images: 'rapyd.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ff027bfc3da9422a9bec26cdb951ef3d }}/rapyd-api:${{ github.sha }}'